# AmigaOS 4.x/PPC

TARGET = _os4
TARGETEXTENSION = 
OUTFMTS = -DOUTAOUT -DOUTBIN -DOUTELF -DOUTHUNK -DOUTSREC -DOUTTOS -DOUTVOBJ

CC = vc +aosppc
CCOUT = -o 
COPTS = -c -DAMIGA -O1 $(OUTFMTS)

LD = $(CC)
LDOUT = $(CCOUT)
LDFLAGS = -lm

RM = delete force quiet

include make.rules
