# Windows compiled on a Linux machine with mingw

TARGET = _win32
TARGETEXTENSION = .exe
OUTFMTS = -DOUTAOUT -DOUTBIN -DOUTELF -DOUTHUNK -DOUTSREC -DOUTTOS -DOUTVOBJ


CC = /usr/bin/i586-mingw32msvc-gcc
CCOUT = -o 
COPTS = -c -O2 $(OUTFMTS)

LD = $(CC)
LDOUT = $(CCOUT)
LDFLAGS = -lm

RM = rm -f



include make.rules
